packages:
  - libs/*
  - demos/*
  - docs-website

catalog:
  '@babel/core': ^7.20.0
  '@babel/helper-module-imports': ^7.0.0
  '@babel/preset-typescript': ^7.24.7
  '@babel/types': ^7.25.6
  '@docusaurus/core': 3.0.1
  '@docusaurus/module-type-aliases': 3.0.1
  '@docusaurus/preset-classic': 3.0.1
  '@docusaurus/tsconfig': 3.0.1
  '@docusaurus/types': 3.0.1
  '@emotion/react': ^11.11.1
  '@emotion/styled': ^11.11.0
  '@eslint/js': ^9.11.1
  '@fontsource/roboto': ^5.0.3
  '@ianvs/prettier-plugin-sort-imports': ^4.4.1
  '@mdx-js/react': ^3.0.0
  '@mui/icons-material': ^5.11.16
  '@prettier/plugin-oxc': 0.0.4
  '@swc/core': 1.7.42
  '@swc/counter': ^0.1.3
  '@types/babel__core': ^7.20.5
  '@types/babel__helper-module-imports': ^7.18.3
  '@types/cosmiconfig': ^5.0.3
  '@types/react': 18.3.1
  '@types/react-dom': 18.3.1
  '@types/react-no-ssr': ^1.1.3
  '@vitejs/plugin-react': ^4.3.2
  babel-plugin-macros: ^2.0.0
  clsx: ^2.0.0
  cors: ^2.8.5
  cosmiconfig: ^5.0.5
  eslint-plugin-react-hooks: ^5.1.0-rc.0
  eslint-plugin-react-refresh: ^0.4.12
  express: ^4.18.2
  express-graphql: ^0.12.0
  globals: ^15.9.0
  graphql-yoga: ^4.0.4
  gulp: 4.0.2
  lorem-ipsum: ^2.0.8
  oxlint: 1.32.0
  oxlint-tsgolint: 0.9.0
  prettier-plugin-hermes-parser: 0.16.0
  prism-react-renderer: ^2.3.0
  react: 18.3.1
  react-dom: 18.3.1
  react-no-ssr: ^1.1.0
  react-test-renderer: ^18.2.0
  react-twitter-embed: ^4.0.4
  rimraf: 6.0.1
  tsdown: 0.20.1
  turbo: ^2.5.6
  typescript: 5.6.3
  typescript-eslint: ^8.7.0
  vite: ^5.4.8
  vite-plugin-babel: ^1.2.0
  vite-plugin-commonjs: ^0.10.1
  vitest: 2.1.9

catalogs:
  peer:
    react: '^18.0.0 || ^19.0.0'

catalogMode: strict

cleanupUnusedCatalogs: true

ignoredBuiltDependencies:
  - '@swc/core'
  - core-js
  - core-js-pure
  - es5-ext
  - esbuild
  - fsevents
  - unrs-resolver

patchedDependencies:
  '@docusaurus/tsconfig': patches/@docusaurus__tsconfig.patch
