packages:
  - libs/*
  - demos/*
  - docs-website
  # if you are working on tree-sitter code, uncomment these lines!
  # - tree-sitter

ignoredBuiltDependencies:
  - '@swc/core'
  - core-js
  - core-js-pure
  - es5-ext
  - esbuild
  - fsevents
  - unrs-resolver

# onlyBuiltDependencies:
#   - tree-sitter
#   - tree-sitter-cli

patchedDependencies:
  '@docusaurus/tsconfig': patches/@docusaurus__tsconfig.patch
