name: Install CLI artifacts
description: Download the five platform CLI artifacts into libs/isograph-compiler/artifacts.

runs:
  using: composite
  steps:
    - name: Download artifact isograph_cli-linux-x64
      uses: actions/download-artifact@v4
      with:
        name: isograph_cli-linux-x64
        path: libs/isograph-compiler/artifacts/linux-x64
    - name: Download artifact isograph_cli-bin-linux-arm64
      uses: actions/download-artifact@v4
      with:
        name: isograph_cli-bin-linux-arm64
        path: libs/isograph-compiler/artifacts/linux-arm64
    - name: Download artifact isograph_cli-macos-x64
      uses: actions/download-artifact@v4
      with:
        name: isograph_cli-macos-x64
        path: libs/isograph-compiler/artifacts/macos-x64
    - name: Download artifact isograph_cli-macos-arm64
      uses: actions/download-artifact@v4
      with:
        name: isograph_cli-macos-arm64
        path: libs/isograph-compiler/artifacts/macos-arm64
    - name: Download artifact isograph_cli-bin-win-x64
      uses: actions/download-artifact@v4
      with:
        name: isograph_cli-bin-win-x64
        path: libs/isograph-compiler/artifacts/win-x64
    - name: Mark binaries as executable
      run: |
        chmod +x libs/isograph-compiler/artifacts/linux-x64/isograph_cli
        chmod +x libs/isograph-compiler/artifacts/linux-arm64/isograph_cli
        chmod +x libs/isograph-compiler/artifacts/macos-x64/isograph_cli
        chmod +x libs/isograph-compiler/artifacts/macos-arm64/isograph_cli
        chmod +x libs/isograph-compiler/artifacts/win-x64/isograph_cli.exe
      shell: bash
