[package]
name = "isograph_parser"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
logos = { workspace = true }
resolve_position = { path = "../resolve_position" }
resolve_position_macros = { path = "../resolve_position_macros" }
safe_peekable = { path = "../safe_peekable" }
scoped_stack = { path = "../scoped_stack" }
span = { path = "../span" }

[lints]
workspace = true
