[package]
name = "isograph_parser"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
logos = { workspace = true }
parser_lang_types = { path = "../parser_lang_types" }
resolve_position = { path = "../resolve_position" }

[lints]
workspace = true
