[package]
name = "isograph_compiler"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
isograph_parser = { path = "../isograph_parser" }
pico = { path = "../pico" }
pico_macros = { path = "../pico_macros" }
span = { path = "../span" }
thiserror = { workspace = true }

[lints]
workspace = true
