name: Build SWC plugin
description: Install the wasm toolchain and build the SWC plugin. Requires pnpm.

runs:
  using: composite
  steps:
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: wasm32-wasip1
        toolchain: stable
        components: rustfmt
        rustflags: '-D warnings -C link-arg=--allow-undefined'
    - uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: musl-tools
        version: 1.0
    - name: Build swc
      run: pnpm build-swc
      shell: bash
