
[package]
authors = ["Robert Balicki <robert.balicki@gmail.com>", "Edmondo Porcu <edmondo.porcu@gmail.com>"]
description = "SWC plugin for Isographv"
edition = "2021"
license = "Apache-2.0"
include = ["Cargo.toml", "src/**/*.rs"]
name = "swc_isograph"
publish = false
version = "0.7.4"

[dependencies]
common_lang_types = { path = "../../common_lang_types" }
intern = { path = "../../../relay-crates/intern" }
isograph_config = { path = "../../isograph_config" }
once_cell = "1.8.0"
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
swc_atoms = "0.6.5"
swc_common = { version = "0.33.17", features = ["concurrent"] }
swc_ecma_ast = "0.112.2"
swc_ecma_utils = "0.127.3"
swc_ecma_visit = "0.98.2"
tracing = {  workspace = true }

[dev-dependencies]
swc_ecma_parser = "0.143.3"
swc_ecma_transforms_testing = "0.140.3"
testing = "0.35.18"
