on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      os:
        required: true
        type: string
      build-name:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
      artifact-file:
        required: true
        type: string
      longpaths:
        required: false
        type: boolean

jobs:
  build:
    name: Build ${{ inputs.artifact-name }}
    timeout-minutes: 15
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ inputs.target }}
      - name: Enable longer pathnames for git
        if: inputs.longpaths
        run: git config --system core.longpaths true
      - name: 'Build isograph (${{inputs.target}})'
        run: cargo build --manifest-path crates/ts_graphql_react_isograph_cli/Cargo.toml --release --target ${{ inputs.target }}
      - name: Name the artifact isograph_cli
        shell: bash
        run: |
          src="target/${{ inputs.target }}/release/${{ inputs.build-name }}"
          mkdir -p artifact
          cp "$src" "artifact/${{ inputs.artifact-file }}"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: artifact/${{ inputs.artifact-file }}
          if-no-files-found: error

  test:
    name: Test ${{ inputs.artifact-name }}
    needs: build
    timeout-minutes: 15
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: artifact
      - name: Make the artifact executable
        if: runner.os != 'Windows'
        run: chmod +x "artifact/${{ inputs.artifact-file }}"
      - name: 'Test isograph (${{inputs.target}})'
        env:
          ISOGRAPH_BIN: ${{ github.workspace }}/artifact/${{ inputs.artifact-file }}
        run: cargo test --manifest-path crates/ts_graphql_react_isograph_cli/Cargo.toml --tests
