name: Build js packages

on:
  workflow_call:

env:
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  build-js-packages:
    name: Build js packages
    runs-on: ubuntu-latest
    timeout-minutes: 15 # in case unit test goes into infinite loop
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-js
        with:
          # see pnpm-workspace.yaml's onlyBuildDependencies for packages that need scripts
          install-args: --frozen-lockfile
      - name: Build
        run: pnpm compile-libs
      - name: Run unit tests
        # unit tests have to run after building, because they rely on Isograph,
        # which relies on @isograph/react being a valid input
        run: pnpm test
