name: JavaScript

on:
  workflow_call:

jobs:
  prettier:
    name: Run prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-js
      - name: Run prettier
        run: pnpm run format-prettier
      - name: Check working directory status
        run: ./scripts/check-git-status.sh

  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-js
      - name: Run lint
        run: pnpm run lint --deny-warnings
