use crate::{
    ArgumentListPath, ArgumentNameWrapperPath, ArgumentPath, ArgumentSlotPath, BooleanValuePath,
    ChunkPath, ChunkSeparatorPath, ChunkedGroupPath, ChunkedLevelPath, CloseBracketPath,
    DescriptionPath, EntityNameWrapperPath, EntrypointDeclarationPath, ExtraChunksPath,
    IntegerValuePath, IsoLiteralParsePath, IsoLiteralSlotPath, IsographDirectiveNameWrapperPath,
    IsographFieldDirectiveListPath, IsographFieldDirectivePath, ListLiteralPath,
    ListLiteralValuePath, ListLiteralValueSlotPath, ListTypeAnnotationPath,
    NamedTypeAnnotationPath, NonBracketTokenPath, NullValuePath, ObjectEntryPath,
    ObjectEntrySlotPath, ObjectLiteralPath, OpenBracketPath, SelectableDeclarationPath,
    SelectableNameWrapperPath, SelectionNameWrapperPath, SelectionPath, SelectionSetPath,
    SelectionSlotPath, StringLiteralValueWrapperPath, UnionTypeAnnotationPath,
    UnparsedChunkItemsPath, ValueKeyNameWrapperPath, VariableDeclarationListPath,
    VariableDeclarationOrUsagePath, VariableDeclarationPath, VariableDeclarationSlotPath,
    VariableNameWrapperPath, VariableUsePath,
};

/// What a position resolves to: the leaves of the newest tree. Each parsing stage
/// modifies these variants in place; today they are the grammar tree's, with the chunk
/// tree's still surfacing inside unparsed regions.
#[derive(Debug)]
#[non_exhaustive]
pub enum IsographResolutionNode<'a> {
    Singleton(IsoLiteralParsePath<'a>),
    IsoLiteralSlot(IsoLiteralSlotPath<'a>),
    EntrypointDeclaration(EntrypointDeclarationPath<'a>),
    SelectableDeclaration(SelectableDeclarationPath<'a>),
    Description(DescriptionPath<'a>),
    EntityNameWrapper(EntityNameWrapperPath<'a>),
    SelectableNameWrapper(SelectableNameWrapperPath<'a>),
    UnparsedChunkItems(UnparsedChunkItemsPath<'a>),
    ExtraChunks(ExtraChunksPath<'a>),
    ChunkedLevel(ChunkedLevelPath<'a>),
    /// This will be resolved for spans that contain one of the opening/closing brackets
    /// and part of the inside, e.g. "{ ba" in "foo { bar }". Single-character spans
    /// will never resolve to this.
    ChunkedGroup(ChunkedGroupPath<'a>),
    Chunk(ChunkPath<'a>),
    ChunkSeparator(ChunkSeparatorPath<'a>),
    NonBracketToken(NonBracketTokenPath<'a>),
    OpenBracket(OpenBracketPath<'a>),
    CloseBracket(CloseBracketPath<'a>),
    ArgumentSlot(ArgumentSlotPath<'a>),
    ObjectEntrySlot(ObjectEntrySlotPath<'a>),
    ArgumentList(ArgumentListPath<'a>),
    ObjectLiteral(ObjectLiteralPath<'a>),
    Argument(ArgumentPath<'a>),
    ObjectEntry(ObjectEntryPath<'a>),
    ArgumentNameWrapper(ArgumentNameWrapperPath<'a>),
    ValueKeyNameWrapper(ValueKeyNameWrapperPath<'a>),
    VariableUse(VariableUsePath<'a>),
    VariableNameWrapper(VariableNameWrapperPath<'a>),
    VariableDeclarationOrUsage(VariableDeclarationOrUsagePath<'a>),
    VariableDeclarationSlot(VariableDeclarationSlotPath<'a>),
    VariableDeclarationList(VariableDeclarationListPath<'a>),
    VariableDeclaration(VariableDeclarationPath<'a>),
    StringLiteralValueWrapper(StringLiteralValueWrapperPath<'a>),
    IntegerValue(IntegerValuePath<'a>),
    BooleanValue(BooleanValuePath<'a>),
    NullValue(NullValuePath<'a>),
    SelectionSlot(SelectionSlotPath<'a>),
    SelectionSet(SelectionSetPath<'a>),
    Selection(SelectionPath<'a>),
    SelectionNameWrapper(SelectionNameWrapperPath<'a>),
    NamedTypeAnnotation(NamedTypeAnnotationPath<'a>),
    ListTypeAnnotation(ListTypeAnnotationPath<'a>),
    UnionTypeAnnotation(UnionTypeAnnotationPath<'a>),
    IsographFieldDirectiveList(IsographFieldDirectiveListPath<'a>),
    IsographFieldDirective(IsographFieldDirectivePath<'a>),
    IsographDirectiveNameWrapper(IsographDirectiveNameWrapperPath<'a>),
    ListLiteral(ListLiteralPath<'a>),
    ListLiteralValue(ListLiteralValuePath<'a>),
    ListLiteralValueSlot(ListLiteralValueSlotPath<'a>),
}
